### PR TITLE
feat: create pull request workflow

### PR DESCRIPTION
**Pull request by lauramargar**

### CODE REVIEW

**Comment by support-empathy** [comment]
[Check **PR 322** preview](https://x.test.empathy.co/preview/322/index.html)

**Comment by support-empathy** [comment]
👀 Check **PR 322** preview <br> [https://x.test.empathy.co/preview/322/index.html](https://x.test.empathy.co/preview/322/index.html)

**Comment by support-empathy** [comment]
Check **PR 322** preview 👀 <br> <br> [https://x.test.empathy.co/preview/322/index.html](https://x.test.empathy.co/preview/322/index.html)

**Comment by support-empathy** [comment]
Check **PR 322** preview 👀 <br> <br> [https://x.test.empathy.co/preview/322/index.html](https://x.test.empathy.co/preview/322/index.html)

**Comment by support-empathy** [comment]
Check **PR 322** preview 👀 <br> <br> [https://x.test.empathy.co/preview/322/index.html](https://x.test.empathy.co/preview/322/index.html)

**Comment by support-empathy** [comment]
Check **PR 322** preview 👀 <br> <br> [https://x.test.empathy.co/preview/322/index.html](https://x.test.empathy.co/preview/322/index.html)

**Comment by support-empathy** [comment]
Check **PR 322** preview 👀 <br> <br> [https://x.test.empathy.co/preview/322/index.html](https://x.test.empathy.co/preview/322/index.html)

**Comment by support-empathy** [comment]
Check **PR 322** preview 👀 <br> <br> [https://x.test.empathy.co/preview/322/index.html](https://x.test.empathy.co/preview/322/index.html)

**Review by diegopf — APPROVED** [review]

**Pull request merged**
