### PR TITLE
fix: styles issues 

### PR DESCRIPTION
**Pull request by diegopf**
EX-6472

### CODE REVIEW

**Review by mavmaf — CHANGES_REQUESTED** [review]
Following our conversation, please find below a summary of change requests:
- Mobile. Add margin to the 'No results' message div
- Desktop. Change query size on total-results to 16px
- Desktop & Mobile. Try to align ID results text titles

**Comment by mnavarroespinosa** [comment]
> Following our conversation, please find below a summary of change requests:
> 
> * Mobile. Add margin to the 'No results' message div
> * Desktop. Change query size on total-results to 16px
> * Desktop & Mobile. Try to align ID results text titles

Fixed the first 2 points, but we cannot align the ID results with the current implementation of the suggestions.

**Review by mavmaf — CHANGES_REQUESTED** [review]
Please take a look to the no results page in mobile. If the query leading to no results is quite long, the text will be misaligned:

**Comment by mnavarroespinosa** [comment]
> Please take a look to the no results page in mobile. If the query leading to no results is quite long, the text will be misaligned: 


Good catch! Fixed!

**Review by mavmaf — DISMISSED** [review]

**Review by tiborux — APPROVED** [review]
gj

**Review by mavmaf — APPROVED** [review]

**Review by tiborux — APPROVED** [review]
gj

**Pull request merged**
