### PR TITLE
feat: deprecate old DS

### PR DESCRIPTION
**Pull request by mnavarroespinosa**
EMP-134

### CODE REVIEW

**Review by herrardo — CHANGES_REQUESTED** [review]
There is a difference on the Next Queries Preview carousel background, I am attaching two images.The margin is narrower now, and we have lost the title "_Those who searched for tshirt also viewed:_"

Staging
image


This PR

**Review by mavmaf — CHANGES_REQUESTED** [review]
🥳 🥳 
Please take a look to the following:

- Desktop. Sort&Filter panel:
- - Text colour for sort and facets panels. Staging: #5E7782; branch: #000000
- - Compare with staging margin/padding for sort list items and facet filters.
- - div containing the close modal button behaviour: whereas in staging has a fixed and visible position, in this branch it disappears with the scrolling (check opening different facet panels)

image

**Comment by mnavarroespinosa** [comment]
> It is something that is wrong on staging but in the partial results, the cursor is not a pointer when you hover the results:
> 
> `dress red iphone`

It is due to the `a` tag not containing the `href` attribute as it is not returned by the search endpoint for the partials:

image

image

**Comment by mnavarroespinosa** [comment]
> 🥳 🥳 Please take a look to the following:
> 
> * Desktop. Sort&Filter panel:
> * * Text colour for sort and facets panels. Staging: #5E7782; branch: #000000
> * * Compare with staging margin/padding for sort list items and facet filters.
> * * div containing the close modal button behaviour: whereas in staging has a fixed and visible position, in this branch it disappears with the scrolling (check opening different facet panels)
> 
> image

@mavmaf The styles for the facets were changed in the Design when the XDS filters were added. We have updated staging again with the latest changes (it was not up to date). The facets in this PR should look now as the designs.

We have fixed the issue with the scroll, you can take a look again. :)

**Review by mavmaf — CHANGES_REQUESTED** [review]
- Mobile. Next query preview, left gap vs no gap in staging
image

**Review by mavmaf — APPROVED** [review]

**Review by herrardo — APPROVED** [review]

**Pull request merged**
